### ISSUE TITLE
while trying to push the artifact from jenkins(CI Job) to nexus.Error:"HTTP method PUT is not supported by this URL".

### ISSUE THREAD

**Issue by AlkaSamant** [xetus-oss/docker-archiva#16]
Return code is: 400, ReasonPhrase: HTTP method PUT is not supported by this URL.
I have been trying multiple ways to resolve this error but i am unable to..
-Checked the location for the repository
-Added correct URL ...
But unable to resolve the error..
Can anyone suggest how can i get rid of this?

05:27:37 [samplegradle-develop-ci] $ /var/jenkins_home/tools/hudson.plugins.gradle.GradleInstallation/gradle/bin/gradle upload
05:27:38 Starting a Gradle Daemon (subsequent builds will be faster)
05:27:47 > Task :compileJava
05:27:47 > Task :processResources NO-SOURCE
05:27:47 > Task :classes
05:27:47 > Task :jar
05:27:49 > Task :javadoc
05:27:49 > Task :javadocJar
05:27:49 > Task :sourcesJar
05:27:53 
05:27:53 > Task :uploadArchives
05:27:53 Could not transfer artifact com.xx.mule.dip.integration:simple-project:jar:2.0-20190711.092752-1 from/to remote (https://repository.xxxxx.com): Failed to transfer file: https://repository.xxx.com/com/lh/mule/dip/integration/simple-project/2.0-SNAPSHOT/simple-project-2.0-20190711.092752-1.jar. Return code is: 400, ReasonPhrase: HTTP method PUT is not supported by this URL.
05:27:55 Could not transfer artifact com.lh.mule.dip.integration:simple-project:pom:2.0-20190711.092752-1 from/to remote (https://repository.xxxxxxx.com): Failed to transfer file: https://repository.xxxxxx.com/com/lh/mule/dip/integration/simple-project/2.0-SNAPSHOT/simple-project-2.0-20190711.092752-1.pom. Return code is: 400, ReasonPhrase: HTTP method PUT is not supported by this URL.

**Comment by tmeneau** [comment]
@AlkaSamant I think you might be in the wrong place. The repository at [repository.liquidhub.com](https://repository.liquidhub.com) is a [Sonatype Nexus artifact repository](https://www.sonatype.com/nexus-repository-sonatype), not an [Apache Archiva repository](https://archiva.apache.org/index.cgi).

If there's a deployed Archiva container that you expect to be reaching at repository.liquidhub.com, you likely need to update upstream routing components (e.g. load balancers, proxies, DNS, etc...). That's something you'll have to investigate.

Otherwise if you are trying to publish to a Nexus repository and just posted in the wrong place there are a few places you can go from here:

1. Verify you've properly configured your Nexus repository. While I've never personally managed a Nexus  deployment it [looks like you don't have any Nexus repositories defined](https://repository.liquidhub.com/#browse/browse).
2. Reach out to [Nexus support](https://support.sonatype.com/hc/en-us) or gather some more info from the [nexus-public Github repo](https://github.com/sonatype/nexus-public).

Either scenario is out of scope for this project so I'm closing this out as a misplaced question, but good luck to you!
