### ISSUE TITLE
How to change archiva path?

### ISSUE THREAD

**Issue by herrmannpchw** [xetus-oss/docker-archiva#7]
Hello, 

I'm trying to change the archiva path to http://X.X.X.X/archiva but had no success. 

Is it possible? How can I change?

Thank you.

**Comment by tkent** [comment]
@herrmannpchw 

That's not a configuration option for this image. Out of question, why do you want to make that change?

**Comment by herrmannpchw** [comment]
I have others services on the same machine with nginx... 

Thanks!

**Comment by tkent** [comment]
@herrmannpchw 

I see. This is a common scenario with container services and a proxy (like nginx) is often used so that everything works.

Here are two simple ways to handle the situation:

1. Configure ngnix to rewrite the requests it receives for "/archiva/XXX" to "/XXX" and forward them to the archiva container's IP. Assuming ngnix is also running in a container, you can use a docker network to make this configuration very simple.

2. Assign an additional IP to the host and bind the archiva container to that new IP. In this case, traffic for Archiva won't go to ngnix. 

Good luck!
