### ISSUE TITLE
Default admin user credentials

### ISSUE THREAD

**Issue by rkamath3** [xetus-oss/docker-archiva#8]
What is the default admin username and password? When I try creating a new user with username 'admin' it says user already exists. However, nowhere in the documentation, the password is mentioned.

**Comment by tkent** [comment]
@rkamath3 

There is no default admin user password for Archiva, which is why you don't see any mentioned in the documentation. When you setup a new Archiva environment, the "login" button on all pages is replaced with a "Create Admin User" button ([see here](https://archiva.apache.org/docs/2.2.3/quick-start.html)).  It's only after you create an admin user that even have the option to login.

It's most likely that whatever data store you're using (MySQL or the embedded db) was setup by a previous Archiva environment. That would explain the confusion you've run into.

Anyway, if you're trying to setup a new Archiva environment:

1. Make sure the data volume you use is an empty directory.
2. Make sure the DB you point the container to is empty.

**Comment by rkamath3** [comment]
@tkent Thanks a lot. There was a docker volume apart from the one I created which had Archiva files. Once cleaned, it worked as desired.

Would you mind adding a Licence to your repo **docker-archiva**? This would help us to make use of the docker image, also reuse the code if needed.
